openapi: 3.0.0
info:
  title: RPP Testbed
  description: RPP Testbed server
  version: 0.0.0
tags:
  - name: Domains
  - name: Contacts
  - name: Hosts
  - name: Poll messages
paths:
  /contacts:
    head:
      operationId: contacts_Check
      parameters:
        - $ref: '#/components/parameters/RequestHeaders'
      responses:
        '200':
          description: The request has succeeded.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactReference'
        '400':
          description: The server could not understand the request due to invalid syntax.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '404':
          description: The server cannot find the requested resource.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse404'
        '500':
          description: Server error
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
      tags:
        - Contacts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactReference'
      security:
        - BasicAuth: []
    post:
      operationId: contacts_Create
      parameters:
        - $ref: '#/components/parameters/RequestHeaders'
        - name: expect
          in: header
          required: false
          schema:
            type: string
            enum:
              - 100-continue
      responses:
        '200':
          description: The request has succeeded.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactReference'
        '400':
          description: The server could not understand the request due to invalid syntax.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '409':
          description: The request conflicts with the current state of the server.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse409'
        '500':
          description: Server error
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
      tags:
        - Contacts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactReference'
      security:
        - BasicAuth: []
  /contacts/{id}:
    get:
      operationId: contacts_Get
      parameters:
        - $ref: '#/components/parameters/RequestHeaders'
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactReference'
        '400':
          description: The server could not understand the request due to invalid syntax.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '404':
          description: The server cannot find the requested resource.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse404'
        '500':
          description: Server error
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
      tags:
        - Contacts
      security:
        - BasicAuth: []
    patch:
      operationId: contacts_Update
      parameters:
        - $ref: '#/components/parameters/RequestHeaders'
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactReference'
        '400':
          description: The server could not understand the request due to invalid syntax.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '404':
          description: The server cannot find the requested resource.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse404'
        '500':
          description: Server error
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
      tags:
        - Contacts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactReferenceUpdate'
      security:
        - BasicAuth: []
  /domains:
    head:
      operationId: domains_Check
      parameters:
        - $ref: '#/components/parameters/RequestHeaders'
      responses:
        '200':
          description: The request has succeeded.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        '400':
          description: The server could not understand the request due to invalid syntax.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '404':
          description: The server cannot find the requested resource.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse404'
        '500':
          description: Server error
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
      tags:
        - Domains
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Domain'
      security:
        - BasicAuth: []
    post:
      operationId: domains_Create
      parameters:
        - $ref: '#/components/parameters/RequestHeaders'
        - name: expect
          in: header
          required: false
          schema:
            type: string
            enum:
              - 100-continue
      responses:
        '200':
          description: The request has succeeded.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        '400':
          description: The server could not understand the request due to invalid syntax.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '409':
          description: The request conflicts with the current state of the server.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse409'
        '500':
          description: Server error
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
      tags:
        - Domains
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DomainCreate'
      security:
        - BasicAuth: []
  /domains/{id}:
    get:
      operationId: domains_Get
      parameters:
        - $ref: '#/components/parameters/RequestHeaders'
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        '400':
          description: The server could not understand the request due to invalid syntax.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '404':
          description: The server cannot find the requested resource.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse404'
        '500':
          description: Server error
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
      tags:
        - Domains
      security:
        - BasicAuth: []
    patch:
      operationId: domains_Update
      parameters:
        - $ref: '#/components/parameters/RequestHeaders'
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        '400':
          description: The server could not understand the request due to invalid syntax.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '404':
          description: The server cannot find the requested resource.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse404'
        '500':
          description: Server error
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
      tags:
        - Domains
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DomainUpdate'
      security:
        - BasicAuth: []
    delete:
      operationId: domains_Delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
      tags:
        - Domains
      security:
        - BasicAuth: []
  /domains/{id}/processes/deletion:
    get:
      operationId: domains_DeletionQuery
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainDeletion'
      tags:
        - Domains
      security:
        - BasicAuth: []
  /domains/{id}/processes/renewal:
    put:
      operationId: domains_RenewalRequest
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainRenewal'
      tags:
        - Domains
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DomainRenewal'
      security:
        - BasicAuth: []
    get:
      operationId: domains_RenewalQuery
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainRenewal'
      tags:
        - Domains
      security:
        - BasicAuth: []
    delete:
      operationId: domains_RenewalCancel
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainRenewal'
      tags:
        - Domains
      security:
        - BasicAuth: []
  /domains/{id}/processes/transfer:
    put:
      operationId: domains_TransferRequest
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainTransfer'
      tags:
        - Domains
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DomainTransfer'
      security:
        - BasicAuth: []
    get:
      operationId: domains_TransferQuery
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainTransfer'
      tags:
        - Domains
      security:
        - BasicAuth: []
    delete:
      operationId: domains_TransferCancel
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainTransfer'
      tags:
        - Domains
      security:
        - BasicAuth: []
  /domains/{id}/processes/transfer/approval:
    put:
      operationId: domains_TransferApprove
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainTransfer'
      tags:
        - Domains
      security:
        - BasicAuth: []
  /domains/{id}/processes/transfer/rejection:
    put:
      operationId: domains_TransferReject
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainTransfer'
      tags:
        - Domains
      security:
        - BasicAuth: []
  /hosts:
    head:
      operationId: hosts_Check
      parameters:
        - $ref: '#/components/parameters/RequestHeaders'
      responses:
        '200':
          description: The request has succeeded.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostInfoAttr'
        '400':
          description: The server could not understand the request due to invalid syntax.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '404':
          description: The server cannot find the requested resource.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse404'
        '500':
          description: Server error
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
      tags:
        - Hosts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HostInfoAttr'
      security:
        - BasicAuth: []
    post:
      operationId: hosts_Create
      parameters:
        - $ref: '#/components/parameters/RequestHeaders'
        - name: expect
          in: header
          required: false
          schema:
            type: string
            enum:
              - 100-continue
      responses:
        '200':
          description: The request has succeeded.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostInfoAttr'
        '400':
          description: The server could not understand the request due to invalid syntax.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '409':
          description: The request conflicts with the current state of the server.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse409'
        '500':
          description: Server error
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
      tags:
        - Hosts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HostInfoAttr'
      security:
        - BasicAuth: []
  /hosts/{id}:
    get:
      operationId: hosts_Get
      parameters:
        - $ref: '#/components/parameters/RequestHeaders'
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostInfoAttr'
        '400':
          description: The server could not understand the request due to invalid syntax.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '404':
          description: The server cannot find the requested resource.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse404'
        '500':
          description: Server error
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
      tags:
        - Hosts
      security:
        - BasicAuth: []
    patch:
      operationId: hosts_Update
      parameters:
        - $ref: '#/components/parameters/RequestHeaders'
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostInfoAttr'
        '400':
          description: The server could not understand the request due to invalid syntax.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '404':
          description: The server cannot find the requested resource.
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse404'
        '500':
          description: Server error
          headers:
            rpp-cltrid:
              required: false
              schema:
                type: string
            rpp-svtrid:
              required: false
              schema:
                type: string
          content:
            application/problem-json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
      tags:
        - Hosts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HostInfoAttrUpdate'
      security:
        - BasicAuth: []
  /messages:
    get:
      operationId: Messages_PollRequest
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
      tags:
        - Poll messages
      security:
        - BasicAuth: []
  /messages/{id}:
    delete:
      operationId: Messages_AckPoll
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
      tags:
        - Poll messages
      security:
        - BasicAuth: []
components:
  parameters:
    RequestHeaders:
      name: rpp-cltrid
      in: header
      required: false
      schema:
        type: string
  schemas:
    Contact:
      type: object
      required:
        - id
        - name
        - address
      properties:
        id:
          type: string
        name:
          type: string
        address:
          type: string
    ContactReference:
      type: object
      required:
        - value
        - type
      properties:
        value:
          type: string
        type:
          type: array
          items:
            $ref: '#/components/schemas/ContactType'
    ContactReferenceUpdate:
      type: object
      properties:
        value:
          type: string
        type:
          type: array
          items:
            $ref: '#/components/schemas/ContactType'
    ContactType:
      type: string
      enum:
        - registrant
        - admin
        - tech
        - billing
    DnsSec:
      type: object
      required:
        - keyTag
        - algorithm
        - digestType
        - digest
      properties:
        keyTag:
          type: string
        algorithm:
          type: string
        digestType:
          type: string
        digest:
          type: string
    Domain:
      type: object
      required:
        - name
        - authInfo
      properties:
        name:
          type: string
        status:
          type: array
          items:
            type: string
        processes:
          type: object
          properties:
            creation:
              $ref: '#/components/schemas/DomainCreation'
            renewal:
              $ref: '#/components/schemas/DomainRenewal'
            transfer:
              $ref: '#/components/schemas/DomainTransfer'
        authInfo:
          type: object
          properties:
            pw:
              type: string
            hash:
              type: string
        ns:
          $ref: '#/components/schemas/NS'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/ContactReference'
        dnsSEC:
          type: array
          items:
            $ref: '#/components/schemas/DnsSec'
        crDate:
          type: string
        exDate:
          type: string
        upDate:
          type: string
        trDate:
          type: string
        clID:
          type: string
        crID:
          type: string
      example:
        name: example.com
        processes:
          creation:
            period: P2Y
        authInfo:
          pw: password
        contacts:
          - value: registrant-id
            type:
              - registrant
    DomainCreate:
      type: object
      required:
        - name
        - authInfo
      properties:
        name:
          type: string
        processes:
          type: object
          properties:
            creation:
              $ref: '#/components/schemas/DomainCreation'
            renewal:
              $ref: '#/components/schemas/DomainRenewal'
            transfer:
              $ref: '#/components/schemas/DomainTransfer'
        authInfo:
          type: object
          properties:
            pw:
              type: string
            hash:
              type: string
        ns:
          $ref: '#/components/schemas/NS'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/ContactReference'
        dnsSEC:
          type: array
          items:
            $ref: '#/components/schemas/DnsSec'
      example:
        name: example.com
        processes:
          creation:
            period: P2Y
        authInfo:
          pw: password
        contacts:
          - value: registrant-id
            type:
              - registrant
    DomainCreation:
      type: object
      properties:
        period:
          type: string
          format: duration
    DomainDeletion:
      type: object
      properties:
        purgeDate:
          type: string
          format: date-time
    DomainRenewal:
      type: object
      properties:
        period:
          type: string
          format: duration
    DomainRequest:
      type: object
      required:
        - name
        - authInfo
      properties:
        name:
          type: string
        status:
          type: array
          items:
            type: string
        processes:
          type: object
          properties:
            creation:
              $ref: '#/components/schemas/DomainCreation'
            renewal:
              $ref: '#/components/schemas/DomainRenewal'
            transfer:
              $ref: '#/components/schemas/DomainTransfer'
        authInfo:
          type: object
          properties:
            pw:
              type: string
            hash:
              type: string
        ns:
          $ref: '#/components/schemas/NS'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/ContactReference'
        dnsSEC:
          type: array
          items:
            $ref: '#/components/schemas/DnsSec'
        crDate:
          type: string
        exDate:
          type: string
        upDate:
          type: string
        trDate:
          type: string
        clID:
          type: string
        crID:
          type: string
    DomainResponse:
      type: object
      required:
        - name
        - authInfo
      properties:
        name:
          type: string
        status:
          type: array
          items:
            type: string
        processes:
          type: object
          properties:
            creation:
              $ref: '#/components/schemas/DomainCreation'
            renewal:
              $ref: '#/components/schemas/DomainRenewal'
            transfer:
              $ref: '#/components/schemas/DomainTransfer'
        authInfo:
          type: object
          properties:
            pw:
              type: string
            hash:
              type: string
        ns:
          $ref: '#/components/schemas/NS'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/ContactReference'
        dnsSEC:
          type: array
          items:
            $ref: '#/components/schemas/DnsSec'
        crDate:
          type: string
        exDate:
          type: string
        upDate:
          type: string
        trDate:
          type: string
        clID:
          type: string
        crID:
          type: string
    DomainTransfer:
      type: object
      properties:
        period:
          type: string
          format: duration
    DomainUpdate:
      type: object
      properties:
        name:
          type: string
        processes:
          type: object
          properties:
            creation:
              $ref: '#/components/schemas/DomainCreation'
            renewal:
              $ref: '#/components/schemas/DomainRenewal'
            transfer:
              $ref: '#/components/schemas/DomainTransfer'
        authInfo:
          type: object
          properties:
            pw:
              type: string
            hash:
              type: string
        ns:
          $ref: '#/components/schemas/NSUpdate'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/ContactReference'
        dnsSEC:
          type: array
          items:
            $ref: '#/components/schemas/DnsSec'
      example:
        name: example.com
        processes:
          creation:
            period: P2Y
        authInfo:
          pw: password
        contacts:
          - value: registrant-id
            type:
              - registrant
    ErrorResponse:
      type: object
      required:
        - title
        - detail
        - type
        - status
        - instance
      properties:
        title:
          type: string
        detail:
          type: string
        type:
          type: string
        status:
          type: string
        instance:
          type: string
    ErrorResponse400:
      type: object
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
    ErrorResponse404:
      type: object
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
    ErrorResponse409:
      type: object
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
    ErrorResponse500:
      type: object
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
    HelloResponse:
      type: object
      required:
        - svID
        - svDate
        - svcMenu
        - dcp
      properties:
        svID:
          type: string
        svDate:
          type: string
        svcMenu:
          type: object
          properties:
            version:
              type: string
            lang:
              type: array
              items:
                type: string
          required:
            - version
            - lang
        dcp:
          type: object
          properties:
            access:
              type: object
              properties:
                all:
                  type: string
              required:
                - all
            statement:
              type: object
              properties:
                purpose:
                  type: object
                  properties:
                    admin:
                      type: string
                    prov:
                      type: string
                  required:
                    - admin
                    - prov
                recipient:
                  type: object
                  properties:
                    ours:
                      type: string
                    public:
                      type: string
                  required:
                    - ours
                    - public
                retention:
                  type: object
                  properties:
                    stated:
                      type: string
                  required:
                    - stated
              required:
                - purpose
                - recipient
                - retention
          required:
            - access
            - statement
    Host:
      type: object
      allOf:
        - $ref: '#/components/schemas/HostInfoAttr'
    HostInfoAttr:
      type: object
      properties:
        addr:
          type: object
          properties:
            ipv4:
              type: array
              items:
                type: string
            ipv6:
              type: array
              items:
                type: string
      allOf:
        - $ref: '#/components/schemas/HostInfoObj'
    HostInfoAttrUpdate:
      type: object
      properties:
        addr:
          type: object
          properties:
            ipv4:
              type: array
              items:
                type: string
            ipv6:
              type: array
              items:
                type: string
      allOf:
        - $ref: '#/components/schemas/HostInfoObjUpdate'
    HostInfoObj:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    HostInfoObjUpdate:
      type: object
      properties:
        name:
          type: string
    HostUpdate:
      type: object
      allOf:
        - $ref: '#/components/schemas/HostInfoAttrUpdate'
    Message:
      type: object
    NS:
      oneOf:
        - $ref: '#/components/schemas/NSHostObj'
        - $ref: '#/components/schemas/NSHostAttr'
    NSHostAttr:
      type: object
      required:
        - hostAttr
      properties:
        hostAttr:
          type: array
          items:
            $ref: '#/components/schemas/HostInfoAttr'
    NSHostAttrUpdate:
      type: object
      properties:
        hostAttr:
          type: array
          items:
            $ref: '#/components/schemas/HostInfoAttr'
    NSHostObj:
      type: object
      required:
        - hostObj
      properties:
        hostObj:
          type: array
          items:
            $ref: '#/components/schemas/HostInfoObj'
    NSHostObjUpdate:
      type: object
      properties:
        hostObj:
          type: array
          items:
            $ref: '#/components/schemas/HostInfoObj'
    NSUpdate:
      oneOf:
        - $ref: '#/components/schemas/NSHostObjUpdate'
        - $ref: '#/components/schemas/NSHostAttrUpdate'
    Registrant:
      type: object
      required:
        - id
      properties:
        id:
          type: string
    ResponseHeaders:
      type: object
  securitySchemes:
    BasicAuth:
      type: http
      scheme: Basic
servers:
  - url: https://localhost:8000
    description: Local RPP Testbed server
    variables: {}
